# Generated by Django 4.1.2 on 2022-10-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_execucao_delete_etapa_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='status',
            field=models.CharField(choices=[('EMB', 'Embargada'), ('5A7', 'Inicio em 5 a 7 dias'), ('3A5', 'Inicio em 3 a 5 dias'), ('1A3', 'Inicio em 1 a 3 dias'), ('INI', 'Já Iniciou')], default='5A7', max_length=3),
        ),
    ]
