# Generated by Django 4.1.2 on 2022-11-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='ordem_processo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
